version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: php83
    ports:
      # by default it's 80, on linux
      - 8000:80
    volumes:
      # on linux the apache server is located on the /var/www/html
      - ./architecture/blog:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3307:3306
    volumes:
      - ./architecture/db.sql:/docker-entrypoint-initdb.d/db.sql
  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - 8899:80
